"""add proxy config to ai models

Revision ID: add_proxy_config_to_ai_models
Revises: add_rich_text_parsing_fields
Create Date: 2025-09-12 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_proxy_config_to_ai_models'
down_revision = 'add_rich_text_parsing_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('use_proxy', sa.Boolean(), nullable=True, comment='是否使用网络代理'))
    op.add_column('ai_models', sa.Column('proxy_url', sa.String(500), nullable=True, comment='代理服务器地址'))
    
    # 设置默认值
    op.execute("UPDATE ai_models SET use_proxy = FALSE WHERE use_proxy IS NULL")
    op.alter_column('ai_models', 'use_proxy', nullable=False, server_default=sa.text('FALSE'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'proxy_url')
    op.drop_column('ai_models', 'use_proxy')
    # ### end Alembic commands ###