"""Pydantic模式包

定义API请求和响应的数据验证模式。
"""

# 基础模式
from .base import (
    BaseResponse,
    ErrorResponse,
    PaginationInfo,
    PaginatedResponse,
    ValidationError,
    ValidationErrorResponse,
    HealthCheckResponse,
    MetricsResponse,
    BulkOperationRequest,
    BulkOperationResponse,
    SearchRequest,
    ExportRequest,
    ImportRequest,
    TaskRequest,
    TaskResponse,
    ConfigItem,
    LogEntry,
    StatisticsResponse
)

# 用户相关模式
from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    UserProfile,
    UserPermissions,
    UserPreferences,
    UserPasswordChange,
    UserPasswordReset,
    UserPasswordResetConfirm,
    UserEmailVerification,
    UserStats,
    UserActivity,
    UserSession,
    TokenResponse,
    RefreshTokenRequest
)

# AI模型相关模式
from .ai_model import (
    ModelType,
    AIModelBase,
    AIModelCreate,
    AIModelUpdate,
    AIModelResponse,
    AIModelHealthCheck,
    AIModelUsage,
    AIModelTest,
    AIModelBatchTest,
    AIModelBatchTestResponse,
    AIModelConfig,
    AIModelMetrics,
    AIModelComparison
)

# 存储凭证相关模式
from .storage_credential import (
    StorageProtocol,
    StorageCredentialBase,
    StorageCredentialCreate,
    StorageCredentialUpdate,
    StorageCredentialResponse,
    StorageCredentialTest,
    StorageCredentialHealthCheck,
    StorageCredentialUsage,
    StorageCredentialStats,
    StorageFileInfo,
    StorageListResponse,
    StorageUploadRequest,
    StorageUploadResponse,
    StorageDownloadRequest,
    StorageDownloadResponse,
    StorageDeleteRequest,
    StorageDeleteResponse,
    StorageBatchOperation,
    StorageBatchOperationResponse
)

# Webhook相关模式
from .webhook import (
    WebhookStatus,
    WebhookEventType,
    WebhookBase,
    WebhookCreate,
    WebhookUpdate,
    WebhookResponse,
    WebhookTest,
    WebhookTestResponse,
    WebhookBatchTest,
    WebhookBatchTestResponse,
    WebhookHealthCheck,
    WebhookUsage,
    WebhookStats,
    WebhookEvent,
    WebhookDelivery,
    WebhookMetrics,
    WebhookFilter,
    WebhookSort
)

# 分析任务相关模式
from .analysis_task import (
    TaskStatus,
    TriggerType,
    TaskPriority,
    FieldConfig,
    MultiFieldConfig,
    AnalysisTaskBase,
    AnalysisTaskCreate,
    AnalysisTaskUpdate,
    AnalysisTaskResponse,
    AnalysisTaskSimpleResponse,
    AnalysisTaskTest,
    AnalysisTaskHealthCheck,
    AnalysisTaskUsage,
    AnalysisTaskStats,
    AnalysisTaskVersion,
    AnalysisTaskClone,
    AnalysisTaskBatchOperation,
    AnalysisTaskBatchOperationResponse,
    AnalysisTaskMetrics,
    AnalysisTaskFilter,
    AnalysisTaskSort,
    MultiFieldTestRequest,
    MultiFieldTestResponse,
    MultiFieldAnalysisTestRequest,
    MultiFieldAnalysisTestResponse
)

# 任务执行相关模式
from .task_execution import (
    ExecutionStatus,
    ExecutionStep,
    TriggerSource,
    TaskExecutionBase,
    TaskExecutionCreate,
    TaskExecutionUpdate,
    TaskExecutionResponse,
    TaskExecutionSummary,
    TaskExecutionCancel,
    TaskExecutionRetry,
    TaskExecutionLog,
    TaskExecutionMetrics,
    TaskExecutionStats,
    TaskExecutionBatchOperation,
    TaskExecutionBatchOperationResponse,
    TaskExecutionFilter,
    TaskExecutionSort
)

# Webhook日志相关模式 - 暂时禁用，待修复模型冲突
# from .webhook_log import (
#     LogStatus,
#     HttpMethod,
#     SecurityLevel,
#     WebhookLogBase,
#     WebhookLogCreate,
#     WebhookLogUpdate,
#     WebhookLogResponse,
#     WebhookLogSummary,
#     WebhookLogStats,
#     WebhookLogClientSummary,
#     WebhookLogPerformanceMetrics,
#     WebhookLogSecuritySummary,
#     WebhookLogArchive,
#     WebhookLogArchiveResponse,
#     WebhookLogFilter,
#     WebhookLogSort
# )

# 系统配置相关模式
from .system_config import (
    ConfigType,
    ConfigCategory,
    ConfigStatus,
    SystemConfigBase,
    SystemConfigCreate,
    SystemConfigUpdate,
    SystemConfigResponse,
    SystemConfigPublicResponse,
    SystemConfigValue,
    SystemConfigValidation,
    SystemConfigValidationResponse,
    SystemConfigReset,
    SystemConfigResetResponse,
    SystemConfigExport,
    SystemConfigImport,
    SystemConfigImportResponse,
    SystemConfigStats,
    SystemConfigHealth,
    SystemConfigFilter,
    SystemConfigSort
)

# 导出所有模式
__all__ = [
    # 基础模式
    "BaseResponse",
    "ErrorResponse",
    "PaginationInfo",
    "PaginatedResponse",
    "ValidationError",
    "ValidationErrorResponse",
    "HealthCheckResponse",
    "MetricsResponse",
    "BulkOperationRequest",
    "BulkOperationResponse",
    "SearchRequest",
    "ExportRequest",
    "ImportRequest",
    "TaskRequest",
    "TaskResponse",
    "ConfigItem",
    "LogEntry",
    "StatisticsResponse",
    
    # 用户相关模式
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "UserProfile",
    "UserPermissions",
    "UserPreferences",
    "UserPasswordChange",
    "UserPasswordReset",
    "UserPasswordResetConfirm",
    "UserEmailVerification",
    "UserStats",
    "UserActivity",
    "UserSession",
    "TokenResponse",
    "RefreshTokenRequest",
    
    # AI模型相关模式
    "ModelType",
    "AIModelBase",
    "AIModelCreate",
    "AIModelUpdate",
    "AIModelResponse",
    "AIModelHealthCheck",
    "AIModelUsage",
    "AIModelTest",
    "AIModelBatchTest",
    "AIModelBatchTestResponse",
    "AIModelConfig",
    "AIModelMetrics",
    "AIModelComparison",
    
    # 存储凭证相关模式
    "StorageProtocol",
    "StorageCredentialBase",
    "StorageCredentialCreate",
    "StorageCredentialUpdate",
    "StorageCredentialResponse",
    "StorageCredentialTest",
    "StorageCredentialHealthCheck",
    "StorageCredentialUsage",
    "StorageCredentialStats",
    "StorageFileInfo",
    "StorageListResponse",
    "StorageUploadRequest",
    "StorageUploadResponse",
    "StorageDownloadRequest",
    "StorageDownloadResponse",
    "StorageDeleteRequest",
    "StorageDeleteResponse",
    "StorageBatchOperation",
    "StorageBatchOperationResponse",
    
    # Webhook相关模式
    "WebhookStatus",
    "WebhookEventType",
    "WebhookBase",
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookResponse",
    "WebhookTest",
    "WebhookTestResponse",
    "WebhookBatchTest",
    "WebhookBatchTestResponse",
    "WebhookHealthCheck",
    "WebhookUsage",
    "WebhookStats",
    "WebhookEvent",
    "WebhookDelivery",
    "WebhookMetrics",
    "WebhookFilter",
    "WebhookSort",
    
    # 分析任务相关模式
    "TaskStatus",
    "TriggerType",
    "TaskPriority",
    "FieldConfig",
    "MultiFieldConfig",
    "AnalysisTaskBase",
    "AnalysisTaskCreate",
    "AnalysisTaskUpdate",
    "AnalysisTaskResponse",
    "AnalysisTaskSimpleResponse",
    "AnalysisTaskTest",
    "AnalysisTaskHealthCheck",
    "AnalysisTaskUsage",
    "AnalysisTaskStats",
    "AnalysisTaskVersion",
    "AnalysisTaskClone",
    "AnalysisTaskBatchOperation",
    "AnalysisTaskBatchOperationResponse",
    "AnalysisTaskMetrics",
    "AnalysisTaskFilter",
    "AnalysisTaskSort",
    "MultiFieldTestRequest",
    "MultiFieldTestResponse",
    "MultiFieldAnalysisTestRequest",
    "MultiFieldAnalysisTestResponse",
    
    # 任务执行相关模式
    "ExecutionStatus",
    "ExecutionStep",
    "TriggerSource",
    "TaskExecutionBase",
    "TaskExecutionCreate",
    "TaskExecutionUpdate",
    "TaskExecutionResponse",
    "TaskExecutionSummary",
    "TaskExecutionCancel",
    "TaskExecutionRetry",
    "TaskExecutionLog",
    "TaskExecutionMetrics",
    "TaskExecutionStats",
    "TaskExecutionBatchOperation",
    "TaskExecutionBatchOperationResponse",
    "TaskExecutionFilter",
    "TaskExecutionSort",
    
    # Webhook日志相关模式 - 暂时禁用
    # "LogStatus",
    # "HttpMethod",
    # "SecurityLevel",
    # "WebhookLogBase",
    # "WebhookLogCreate",
    # "WebhookLogUpdate",
    # "WebhookLogResponse",
    # "WebhookLogSummary",
    # "WebhookLogStats",
    # "WebhookLogClientSummary",
    # "WebhookLogPerformanceMetrics",
    # "WebhookLogSecuritySummary",
    # "WebhookLogArchive",
    # "WebhookLogArchiveResponse",
    # "WebhookLogFilter",
    # "WebhookLogSort",
    
    # 系统配置相关模式
    "ConfigType",
    "ConfigCategory",
    "ConfigStatus",
    "SystemConfigBase",
    "SystemConfigCreate",
    "SystemConfigUpdate",
    "SystemConfigResponse",
    "SystemConfigPublicResponse",
    "SystemConfigValue",
    "SystemConfigValidation",
    "SystemConfigValidationResponse",
    "SystemConfigReset",
    "SystemConfigResetResponse",
    "SystemConfigExport",
    "SystemConfigImport",
    "SystemConfigImportResponse",
    "SystemConfigStats",
    "SystemConfigHealth",
    "SystemConfigFilter",
    "SystemConfigSort",
]

# 版本信息
__version__ = "1.0.0"
__author__ = "飞书项目AI团队"